[package]
name = "identity-diff-derive"
version = "0.6.4"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity"]
license = "Apache-2.0"
readme = "./README.md"
repository = "https://github.com/iotaledger/identity.rs"
description = "Derive procedural macro for the identity-diff crate."

[lib]
name = "identity_diff_derive"
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
quote = { version = "1.0" }
serde = { version = "1.0" }
syn = { version = "1.0", features = ["extra-traits", "parsing", "derive"] }
