blank_issues_enabled: false
contact_links:
  - name: Official Discord
    url: https://discord.iota.org/
    about: Contact the maintainers by joining the official Discord. Look for the channel #identity-discussions. 
