[package]
name = "identity_derive"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A proc macro library for Diffing Structures"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "identity_derive"
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["extra-traits", "parsing"] }
proc-macro2 = "1.0"
quote = "1.0"
serde = "1.0"

[dev-dependencies]
identity_diff = {path = "../identity_diff", version = "0.1.0", features = ["diff_derive"]}
serde_json = "1.0"