[package]
name = "identity_proof"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "An implementation of Linked Data Proofs."
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
canonical_json = { git = "https://github.com/l1h3r/canonicaljson-rs", branch = "force-map-order" }
identity_core = { path = "../identity_core" }
identity_crypto = { path = "../identity_crypto" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "1.0"
