[package]
name = "identity-actor"
version = "0.5.0-dev.4"
authors = ["IOTA Stiftung"]
edition = "2021"
homepage = "https://www.iota.org"
keywords = ["iota", "tangle", "identity"]
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
description = "A peer-to-peer identity communication framework"

[dependencies]
async-trait = "0.1"
dashmap = "4"
futures = "0.3"
identity-account = { path = "../identity-account", default-features = false, optional = true }
identity-core = { path = "../identity-core" }
identity-iota = { path = "../identity-iota", default-features = false }
libp2p = { version = "0.42", default-features = false, features = ["tcp-tokio", "dns-tokio", "websocket", "request-response", "noise", "yamux"] }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["rt"] }
uuid = { version = "0.8", features = ["v4", "serde"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["stable"] }
pretty_env_logger = "0.4"

[[bench]]
name = "benchmark"
harness = false

[features]
account = ["identity-account/mem-client", "identity-account/async"]
default = ["account"]
