[package]
name = "identity-actor"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
license = "Apache-2.0"
description = "A peer-to-peer identity communication framework"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
async-trait = "0.1.50"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
futures = "0.3"
identity-account = { path = "../identity-account", default-features = false, optional = true }
identity-core = { path = "../identity-core" }
identity-did = { path = "../identity-did" }
identity-iota = { path = "../identity-iota", default-features = false }
dashmap = "4.0"
tokio = { version = "1.7", features = ["rt"] }
libp2p = { version = "0.39", default-features = false, features = [
    "tcp-async-io",
] }

[dependencies.stronghold-communication-refactored]
git = "https://github.com/iotaledger/stronghold.rs"
rev = "442f846d489f98c9913f8d06a3c2e9daa8151afc"
default-features = false

[dev-dependencies]
anyhow = "1.0"
pretty_env_logger = "0.4.0"

[features]
account = ["identity-account/default"]
wasm = ["identity-iota/wasm", "identity-account/wasm"]
tcp = ["stronghold-communication-refactored/tcp-transport"]
websocket = ["libp2p/websocket"]
default = ["account", "tcp", "websocket"]
