[package]
name = "identity-iota"
version = "0.2.0"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "An IOTA Tangle intergration for the identity-rs library."
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

[dependencies]
async-trait = { version = "0.1", default-features = false }
futures = { version = "0.3" }
identity-core = { version = "=0.2.0", path = "../identity-core" }
identity-credential = { version = "=0.2.0", path = "../identity-credential" }
identity-did = { version = "=0.2.0", path = "../identity-did" }
iota-constants = { version = "0.2", default-features = false }
iota-conversion = { version = "0.5", default-features = false }
lazy_static = { version = "1.4", default-features = false }
log = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
thiserror = { version = "1.0", default-features = false }

[dependencies.iota-core]
git = "https://github.com/iotaledger/iota.rs"
rev = "2b84478c71b0078d7776974bb066bd7aa74cea38"
default-features = false
features = ["wasm"]

[dependencies.iota-crypto]
version = "0.5"
features = ["blake2b"]

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features --no-deps --workspace --open
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
