name: Version

on:
  push:
    branches:
      - dev
      - release/*
      - hotfix/*
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - name: Get current branch name
        run: |
          BRANCHNAME=$(git rev-parse --abbrev-ref HEAD)
          echo BRANCHNAME=$BRANCHNAME
          echo BRANCHNAME=$BRANCHNAME >> $GITHUB_ENV
      - name: Determine next version
        run: |
          BRANCHNAME=${{ env.BRANCHNAME }}
          if [[ $BRANCHNAME == release/* || $BRANCHNAME == hotfix/* ]]; then
            NEXTVERSION=${BRANCHNAME##*/}
          fi

          echo NEXTVERSION=$NEXTVERSION
          NEXTVERSION_ARG=$(if [ $NEXTVERSION != '' ]; then echo --future-release $NEXTVERSION; fi)
          echo NEXTVERSION_ARG=$NEXTVERSION_ARG >> $GITHUB_ENV
      - name: Prepare repository
        run: |
          GITHUB_REPOSITORY_USER=$( echo $GITHUB_REPOSITORY | awk -F'/' '{print $1}') 
          GITHUB_REPOSITORY_PROJECT=$( echo $GITHUB_REPOSITORY | awk -F'/' '{print $2}') 

          echo GITHUB_REPOSITORY_USER=$GITHUB_REPOSITORY_USER
          echo GITHUB_REPOSITORY_PROJECT=$GITHUB_REPOSITORY_PROJECT

          echo GITHUB_REPOSITORY_USER=$GITHUB_REPOSITORY_USER >> $GITHUB_ENV
          echo GITHUB_REPOSITORY_PROJECT=$GITHUB_REPOSITORY_PROJECT >> $GITHUB_ENV
      - name: Run github-changelog-generator
        uses: docker://githubchangeloggenerator/github-changelog-generator
        with:
          args: >
            --config-file .github/.github_changelog_generator
            --user ${{ env.GITHUB_REPOSITORY_USER }}
            --project ${{ env.GITHUB_REPOSITORY_PROJECT }} 
            --token ${{ secrets.GITHUB_TOKEN }} 
            ${{ env.NEXTVERSION_ARG }} 
            --exclude-tags-regex "dev-\d{1,}"
      - name: Log CHANGELOG.md
        run: cat CHANGELOG.md
      - name: Commit changes
        run: |
          if [[ $(git diff --stat) == '' ]]; then
            echo 'CHANGELOG.md unmodified'
            exit 0
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f CHANGELOG.md
          git commit -m "generate Changelog"
          git push


      
