[package]
name = "identity_pqc_verifier"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords = ["iota", "identity", "jose", "jwk", "jws"]
license.workspace = true
readme = "./README.md"
repository.workspace = true
rust-version.workspace = true
description = "JWS PQC signature verification for IOTA Identity"

[dependencies]
identity_jose = { version = "=1.1.0-alpha.1", path = "../identity_jose", default-features = false }
oqs = {version = "0.9.0", default-features = false, features = ["sigs", "std", "vendored"] }

[features]
ML_DSA_44 = []
ML_DSA_65 = []
ML_DSA_87 = []
SLH_DSA_SHA2_128s = []
SLH_DSA_SHA2_128f = []
SLH_DSA_SHAKE_128s = []

SLH_DSA_SHAKE_128f = []
SLH_DSA_SHA2_192s = []
SLH_DSA_SHAKE_192s = []
SLH_DSA_SHA2_192f = []
SLH_DSA_SHAKE_192f = []
SLH_DSA_SHA2_256s = []
SLH_DSA_SHAKE_256s = []
SLH_DSA_SHA2_256f = []
SLH_DSA_SHAKE_256f = []

FALCON512 = []
FALCON1024 = []

default = [
    "ML_DSA_44", 
    "ML_DSA_65", 
    "ML_DSA_87", 
    "SLH_DSA_SHA2_128s", 
    "SLH_DSA_SHA2_128f", 
    "SLH_DSA_SHAKE_128s",

    "SLH_DSA_SHAKE_128f",
    "SLH_DSA_SHA2_192s",
    "SLH_DSA_SHAKE_192s",
    "SLH_DSA_SHA2_192f",
    "SLH_DSA_SHAKE_192f",
    "SLH_DSA_SHA2_256s",
    "SLH_DSA_SHAKE_256s",
    "SLH_DSA_SHA2_256f",
    "SLH_DSA_SHAKE_256f",

    "FALCON512",
    "FALCON1024",
    ]