[package]
name = "iota_identity-stronghold-nodejs"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.0", default-features = false, features = ["napi4", "serde-json"] }
napi-derive = "2.12.2"
identity_iota = { version = "0.7.0-alpha.6", path = "../../identity_iota", default-features = false }
identity_core = { version = "0.7.0-alpha.6", path = "../../identity_core", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
