comment_width = 120
format_code_in_doc_comments = true
license_template_path = ".license_template"
max_width = 120
normalize_comments = false
normalize_doc_attributes = false
tab_spaces = 2
wrap_comments = true
imports_granularity = "Item"
